### ISSUE TITLE
Type ./src in the App location box.

### ISSUE THREAD

**Issue by zen37** [rochabr/reactor-ais#1]
_Select Custom from the Build Presets dropdown.
Type ./src in the App location box.
Leave the Api location box empty.
Type ./src App artifact location box._

It should be:

_Select Custom from the Build Presets dropdown.
Type / in the App location box.
Leave the Api location box empty.
Type / App artifact location box._

**Comment by rochabr** [comment]
Thank you for pointing this out, @zen37. The location of the webpage code will depend on how you setup your code structure. In this case it is on the root folder.
